pipeline:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
      - GOPATH=/drone
    commands:
      - make vet
      - make build
      - make test
  docker:
    storage_driver: overlay
    repo: plugins/drone-s3
    tag: [ "latest" ]
    when:
      branch: release/0.4
      event: push

plugin:
  name: S3
  desc: Publish files and artifacts to Amazon S3
  type: publish
  image: plugins/drone-s3
  labels:
    - publish
    - artifacts
    - amazon
    - aws
    - s3
